name: Cleanup Old Previews

on:
  schedule:
    - cron: "0 2 * * *" # ежедневно в 02:00 UTC

permissions:
  contents: read

jobs:
  cleanup-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup old preview directories
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            find /var/www/lift-preview -maxdepth 1 -mindepth 1 -type d -mtime +7 -exec rm -rf {} +
